YourStudioFinal/Controllers/Gallery/GalleryCustomerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YourStudioFinal.Controllers.Home;
using YourStudioFinal.data;
using YourStudioFinal.Models;
using YourStudioFinal.Models.Gallery;

namespace YourStudioFinal.Controllers.Gallery;

public class GalleryCustomerController : Controller
{
    private readonly ILogger<GalleryCustomerController> _logger;
    
    private readonly UserManager<User> _userManager;
    private readonly SignInManager<User> _signInManager;
    private readonly ApplicationDbContext _context;
    public GalleryCustomerController(ILogger<GalleryCustomerController> logger , UserManager<User> userManager, SignInManager<User> signInManager, ApplicationDbContext context)
    {
        _logger = logger;
        _userManager = userManager;
        _signInManager = signInManager;
        _context = context;
    }
    
    public async Task<IActionResult> Index()
    {
        var gallery = await _context.Gallery.FirstOrDefaultAsync();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }

        if (gallery == null)
        {
            gallery = new Models.Gallery.Gallery();
            gallery.Id = Guid.NewGuid().ToString();
            gallery.GalleryFiles = new();
            _context.Gallery.Add(gallery);
            await _context.SaveChangesAsync();
            gallery = await _context.Gallery.FirstOrDefaultAsync();
        }
        else
        {
            var files = _context.GalleryFiles.Where(e => e.GalleryId == gallery.Id).OrderByDescending(e => e.DateUploaded);
            gallery.GalleryFiles = files.ToList();
        }

        return View(gallery);
    }
    
    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Index", "Account");
    }

    public async Task<ActionResult> SoloIndex()
    {
        var gallery = await _context.Gallery.FirstOrDefaultAsync();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }

        if (gallery == null)
        {
            gallery = new Models.Gallery.Gallery();
            gallery.Id = Guid.NewGuid().ToString();
            gallery.GalleryFiles = new();
            _context.Gallery.Add(gallery);
            await _context.SaveChangesAsync();
            gallery = await _context.Gallery.FirstOrDefaultAsync();
        }
        else
        {
            var files = _context.GalleryFiles.Where(e => e.GalleryId == gallery.Id).OrderByDescending(x => x.DateUploaded).Where(e => e.category == "Solo");
            gallery.GalleryFiles = files.ToList();
        }

        return View(gallery);
    }
    
    public async Task<ActionResult> FurIndex()
    {
        var gallery = await _context.Gallery.FirstOrDefaultAsync();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }

        if (gallery == null)
        {
            gallery = new Models.Gallery.Gallery();
            gallery.Id = Guid.NewGuid().ToString();
            gallery.GalleryFiles = new();
            _context.Gallery.Add(gallery);
            await _context.SaveChangesAsync();
            gallery = await _context.Gallery.FirstOrDefaultAsync();
        }
        else
        {
            var files = _context.GalleryFiles.Where(e => e.category == "Fur Families").OrderByDescending(x => x.DateUploaded).Where(e => e.GalleryId == gallery.Id);
            gallery.GalleryFiles = files.ToList();
        }

        return View(gallery);
    }
    
    public async Task<ActionResult> FamilyIndex()
    {
        var gallery = await _context.Gallery.FirstOrDefaultAsync();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }

        if (gallery == null)
        {
            gallery = new Models.Gallery.Gallery();
            gallery.Id = Guid.NewGuid().ToString();
            gallery.GalleryFiles = new();
            _context.Gallery.Add(gallery);
            await _context.SaveChangesAsync();
            gallery = await _context.Gallery.FirstOrDefaultAsync();
        }
        else
        {
            var files = _context.GalleryFiles.Where(e => e.category == "Family").OrderByDescending(x => x.DateUploaded).Where(e => e.GalleryId == gallery.Id);
            gallery.GalleryFiles = files.ToList();
        }

        return View(gallery);
    }
    
    public async Task<ActionResult> CoupleIndex()
    {
        var gallery = await _context.Gallery.FirstOrDefaultAsync();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }

        if (gallery == null)
        {
            gallery = new Models.Gallery.Gallery();
            gallery.Id = Guid.NewGuid().ToString();
            gallery.GalleryFiles = new();
            _context.Gallery.Add(gallery);
            await _context.SaveChangesAsync();
            gallery = await _context.Gallery.FirstOrDefaultAsync();
        }
        else
        {
            var files = _context.GalleryFiles.Where(e => e.category == "Couples").OrderByDescending(x => x.DateUploaded).Where(e => e.GalleryId == gallery.Id);
            gallery.GalleryFiles = files.ToList();
        }

        return View(gallery);
    }

}

YourStudioFinal/Views/GalleryCustomer/CoupleIndex.cshtml
@{
    
    ViewBag.Title = "Gallery";
    
}


<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/homegallery/gallerycustomer.css" asp-append-version="true" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>


<body style="background-image: url(/assets/Background.png);">

    <header>
    </header>

    <p class="text-center">
        <span class="gall">GALLERY</span>

    </p>


    <div class="nav2list-position">
        <ul class="nav2list">
            <li class="nav2">

                @Html.ActionLink("All", "Index", "GalleryCustomer", null, new { @class = "black-text" }) &nbsp;         |&nbsp;
            </li>
            <li class="nav2">
                @Html.ActionLink("SoloIto", "SoloIndex", "GalleryCustomer", null, new { @class = "black-text" }) &nbsp;      |&nbsp;
            </li>
            <li class="nav2">
                &nbsp;
                @Html.ActionLink("Family", "FamilyIndex", "GalleryCustomer", null, new { @class = "black-text" }) &nbsp;       |&nbsp;
            </li>
            <li class="nav2">
                @Html.ActionLink("Duo", "FurIndex", "GalleryCustomer", null, new { @class = "black-text" }) &nbsp;      |&nbsp;

            </li>
            <li class="nav2">
                @Html.ActionLink("Barkada", "CoupleIndex", "GalleryCustomer", null, new { @class = "black-text", @style = "color: #d18d06" })

            </li>

        </ul>


    </div>



    <div class="container">
        @{
            if (Model.GalleryFiles.Count == 0)
            {
                <text>
                    <p class="noitems"> No items found </p>
                </text>
            }
            else
            {
                for (int i = 0; i < Model.GalleryFiles.Count; i++)
                {
                    <div class="responsive">
                        <div class="gallery">
                            <a target="_blank">
                                <img src="@System.IO.Path.Combine("../uploads", Model.GalleryFiles[i].fileName)" alt="Forest" width="600" height="400">
                            </a>
                        </div>
                    </div>
                }
            }
        }
    </div>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>



    <script src="https://cdjns.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


    



</body>



</html>

<footer>
    <div class="footer-container">
        <hr />
        <div class="social-icons">
            <a href="https://www.waze.com/live-map/directions?to=ll.14.451163%2C120.951211" target="_blank"><i class="fa-brands fa-waze fa-2x"></i></a>
            <a href="https://www.facebook.com/YourStudio.bacoor" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a>
            <a href="https://www.instagram.com/yourstudio.bacoor/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
        </div>
    </div>
    <p class="copyright">&copy; 2023 Your Studio</p>
</footer>

YourStudioFinal/Views/GalleryCustomer/FamilyIndex.cshtml
@{
    
    ViewBag.Title = "Gallery";
    
}


<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/homegallery/gallerycustomer.css" asp-append-version="true" />

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>


<body style="background-image: url(/assets/Background.png);">

    <header>
    </header>

    <p class="text-center">
        <span class="gall">GALLERY</span>

    </p>


    <div class="nav2list-position">
        <ul class="nav2list">
            <li class="nav2">

                @Html.ActionLink("All", "Index", "GalleryCustomer", null, new { @class = "black-text" }) &nbsp;         |&nbsp;
            </li>
            <li class="nav2">
                @Html.ActionLink("SoloIto", "SoloIndex", "GalleryCustomer", null, new { @class = "black-text" }) &nbsp;      |&nbsp;
            </li>
            <li class="nav2">
                &nbsp;
                @Html.ActionLink("Family", "FamilyIndex", "GalleryCustomer", null, new { @class = "black-text", @style = "color: #d18d06" }) &nbsp;       |&nbsp;
            </li>
            <li class="nav2">
                @Html.ActionLink("Duo", "FurIndex", "GalleryCustomer", null, new { @class = "black-text" }) &nbsp;      |&nbsp;

            </li>
            <li class="nav2">
                @Html.ActionLink("Barkada", "CoupleIndex", "GalleryCustomer", null, new { @class = "black-text" }) &nbsp;

            </li>

        </ul>


    </div>



    <div class="container">
        @{
            if (Model.GalleryFiles.Count == 0)
            {
                <text>
                    <p class="noitems"> No items found </p>
                </text>
            }
            else
            {
                for (int i = 0; i < Model.GalleryFiles.Count; i++)
                {
                    <div class="responsive">
                        <div class="gallery">
                            <a target="_blank">
                                <img src="@System.IO.Path.Combine("../uploads", Model.GalleryFiles[i].fileName)" alt="Forest" width="600" height="400">
                            </a>
                        </div>
                    </div>
                }
            }
        }
    </div>
    <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.js"
            asp-fallback-src="~/lib/jquery/dist/jquery.js"
            asp-fallback-test="window.jQuery"
            crossorigin="anonymous"
            integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
    </script>



    <script src="https://cdjns.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>

    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.12.9/dist/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.0.0/dist/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


   



</body>



</html>

<footer>
    <div class="footer-container">
        <hr />
        <div class="social-icons">
            <a href="https://www.waze.com/live-map/directions?to=ll.14.451163%2C120.951211" target="_blank"><i class="fa-brands fa-waze fa-2x"></i></a>
            <a href="https://www.facebook.com/YourStudio.bacoor" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a>
            <a href="https://www.instagram.com/yourstudio.bacoor/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
        </div>
    </div>
    <p class="copyright">&copy; 2023 Your Studio</p>
</footer>