YourStudioFinal/Models/Gallery/Gallery.cs
namespace YourStudioFinal.Models.Gallery;

public class Gallery
{
    // TODO:
    //public User associatedUser { get; set; }
    public string Id { get; set; }

    public List<GalleryFile> GalleryFiles { get; set; } = new();
}

YourStudioFinal/Models/Gallery/GalleryFile.cs
namespace YourStudioFinal.Models.Gallery;

public class GalleryFile
{
    public string Id { get; set; }
    public string fileName { get; set; }
    public string category { get; set; }
    
    public DateTime DateUploaded { get; set; }
    
    public string GalleryId { get; set; } = null!;
    public Gallery Gallery { get; set; } = null!;
}

YourStudioFinal/Controllers/Gallery/GalleryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YourStudioFinal.data;
using YourStudioFinal.Models;
using YourStudioFinal.Models.Gallery;

namespace YourStudioFinal.Controllers
{
    [Authorize(Roles = "Admin")]
    public class GalleryController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<User> _userManager;

        public GalleryController(ApplicationDbContext context, UserManager<User> userManager)
        {
            _context = context;
            _userManager = userManager;
        }

        public async Task<IActionResult> CoupleAdminIndex()
        {
            var UserDetails = await _userManager.GetUserAsync(User);
            if (UserDetails != null)
            {
                ViewBag.User = UserDetails;
                ViewBag.isLogged = true;
            }
            else
            {
                ViewBag.isLogged = false;
            }
            
            var gallery = await _context.Gallery.FirstOrDefaultAsync();

            if (gallery == null)
            {
                gallery = new Models.Gallery.Gallery();
                gallery.Id = Guid.NewGuid().ToString();
                gallery.GalleryFiles = new();
                _context.Gallery.Add(gallery);
                await _context.SaveChangesAsync();
                gallery = await _context.Gallery.FirstOrDefaultAsync();
            }
            else
            {
                var files = _context.GalleryFiles.Where(e => e.GalleryId == gallery.Id).OrderByDescending(x => x.DateUploaded)
                    .Where(x => x.category == "Couples");
                gallery.GalleryFiles = files.ToList();
            }

            return View(gallery);
        }
        
        public async Task<IActionResult> FamilyAdminIndex()
        {
            var UserDetails = await _userManager.GetUserAsync(User);
            if (UserDetails != null)
            {
                ViewBag.User = UserDetails;
                ViewBag.isLogged = true;
            }
            else
            {
                ViewBag.isLogged = false;
            }
            
            var gallery = await _context.Gallery.FirstOrDefaultAsync();

            if (gallery == null)
            {
                gallery = new Models.Gallery.Gallery();
                gallery.Id = Guid.NewGuid().ToString();
                gallery.GalleryFiles = new();
                _context.Gallery.Add(gallery);
                await _context.SaveChangesAsync();
                gallery = await _context.Gallery.FirstOrDefaultAsync();
            }
            else
            {
                var files = _context.GalleryFiles.Where(e => e.GalleryId == gallery.Id).OrderByDescending(x => x.DateUploaded)
                    .Where(x => x.category == "Family");
                gallery.GalleryFiles = files.ToList();
            }

            return View(gallery);
        }
        
        public async Task<IActionResult> FurAdminIndex()
        {
            var UserDetails = await _userManager.GetUserAsync(User);
            if (UserDetails != null)
            {
                ViewBag.User = UserDetails;
                ViewBag.isLogged = true;
            }
            else
            {
                ViewBag.isLogged = false;
            }
            
            var gallery = await _context.Gallery.FirstOrDefaultAsync();

            if (gallery == null)
            {
                gallery = new Models.Gallery.Gallery();
                gallery.Id = Guid.NewGuid().ToString();
                gallery.GalleryFiles = new();
                _context.Gallery.Add(gallery);
                await _context.SaveChangesAsync();
                gallery = await _context.Gallery.FirstOrDefaultAsync();
            }
            else
            {
                var files = _context.GalleryFiles.Where(e => e.GalleryId == gallery.Id).OrderByDescending(x => x.DateUploaded)
                    .Where(x => x.category == "Fur Families");
                gallery.GalleryFiles = files.ToList();
            }

            return View(gallery);
        }
        
        public async Task<IActionResult> SoloAdminIndex()
        {
            var UserDetails = await _userManager.GetUserAsync(User);
            if (UserDetails != null)
            {
                ViewBag.User = UserDetails;
                ViewBag.isLogged = true;
            }
            else
            {
                ViewBag.isLogged = false;
            }
            
            var gallery = await _context.Gallery.FirstOrDefaultAsync();

            if (gallery == null)
            {
                gallery = new Models.Gallery.Gallery();
                gallery.Id = Guid.NewGuid().ToString();
                gallery.GalleryFiles = new();
                _context.Gallery.Add(gallery);
                await _context.SaveChangesAsync();
                gallery = await _context.Gallery.FirstOrDefaultAsync();
            }
            else
            {
                var files = _context.GalleryFiles.Where(e => e.GalleryId == gallery.Id).OrderByDescending(x => x.DateUploaded).Where(x => x.category == "Solo");
                gallery.GalleryFiles = files.ToList();
            }

            return View(gallery);
        }

        public async Task<IActionResult> Index()
        {
            var UserDetails = await _userManager.GetUserAsync(User);
            if (UserDetails != null)
            {
                ViewBag.User = UserDetails;
                ViewBag.isLogged = true;
            }
            else
            {
                ViewBag.isLogged = false;
            }
            
            var gallery = await _context.Gallery.FirstOrDefaultAsync();

            if (gallery == null)
            {
                gallery = new Models.Gallery.Gallery();
                gallery.Id = Guid.NewGuid().ToString();
                gallery.GalleryFiles = new();
                _context.Gallery.Add(gallery);
                await _context.SaveChangesAsync();
                gallery = await _context.Gallery.FirstOrDefaultAsync();
            }
            else
            {
                var files = _context.GalleryFiles.Where(e => e.GalleryId == gallery.Id).OrderByDescending(x => x.DateUploaded);
                gallery.GalleryFiles = files.ToList();
            }

            return View(gallery);
        }

        public async Task<IActionResult> Upload([FromForm(Name = "image")] IFormFileCollection files, [FromForm(Name="category")] string formCategory)
        {
            // TODO link to user data
            var currentGallery = await _context.Gallery.FirstOrDefaultAsync();

            // list of files to add to the gallery
            List<GalleryFile> f = new List<GalleryFile>();

            if (files.Count == 0)
                return RedirectToAction("Index");

            // Ensure that the uploads directory exists
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", currentGallery.Id);
            if (!Path.Exists(filePath))
            {
                Directory.CreateDirectory(filePath);
            }

            foreach (var file in files)
            {
                if (file.Length > int.MaxValue)
                {
                    ViewBag.Error = "File is too large";
                    return RedirectToAction("Index");
                }
            }

            foreach (var file in files)
            {
                var _path = Path.Combine(filePath, file.FileName);
                await using (var fileStream = new FileStream(_path, FileMode.Create))
                {
                    // Create the file...
                    await file.CopyToAsync(fileStream);

                    // Create an entry into the database
                    var galleryFile = new GalleryFile();

                    // Set the file id and the gallery it's attached to
                    galleryFile.Id = Guid.NewGuid().ToString();
                    galleryFile.fileName = Path.Combine(currentGallery.Id, file.FileName);
                    galleryFile.Gallery = currentGallery;
                    galleryFile.category = formCategory;
                    galleryFile.DateUploaded = DateTime.Now;

                    // Add the files to the gallery dbset
                    _context.GalleryFiles.Add(galleryFile);

                    // Add the file to the list of files to add to the gallery
                    f.Add(galleryFile);

                    // Ensure the file is written to disk
                    await fileStream.FlushAsync();
                }
            }

            // Save the gallery
            currentGallery.GalleryFiles = f;
            _context.Gallery.Update(currentGallery);
            

            // Save and reload page
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }
        
        [HttpPost]
        public async Task<IActionResult> Delete(string ids)
        {
            var idList = ids.Split(",");
            
            
            foreach (var id in idList)
            {
                var galleryFile = await _context.GalleryFiles.FirstOrDefaultAsync(e => e.Id == id);
                if (galleryFile != null)
                {
                    _context.GalleryFiles.Remove(galleryFile);
                    await _context.SaveChangesAsync();
                }
            }

            return RedirectToAction("Index");
        }
        
    }
}

YourStudioFinal/Controllers/Gallery/GalleryCustomerController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YourStudioFinal.Controllers.Home;
using YourStudioFinal.data;
using YourStudioFinal.Models;
using YourStudioFinal.Models.Gallery;

namespace YourStudioFinal.Controllers.Gallery;

public class GalleryCustomerController : Controller
{
    private readonly ILogger<GalleryCustomerController> _logger;
    
    private readonly UserManager<User> _userManager;
    private readonly SignInManager<User> _signInManager;
    private readonly ApplicationDbContext _context;
    public GalleryCustomerController(ILogger<GalleryCustomerController> logger , UserManager<User> userManager, SignInManager<User> signInManager, ApplicationDbContext context)
    {
        _logger = logger;
        _userManager = userManager;
        _signInManager = signInManager;
        _context = context;
    }
    
    public async Task<IActionResult> Index()
    {
        var gallery = await _context.Gallery.FirstOrDefaultAsync();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }

        if (gallery == null)
        {
            gallery = new Models.Gallery.Gallery();
            gallery.Id = Guid.NewGuid().ToString();
            gallery.GalleryFiles = new();
            _context.Gallery.Add(gallery);
            await _context.SaveChangesAsync();
            gallery = await _context.Gallery.FirstOrDefaultAsync();
        }
        else
        {
            var files = _context.GalleryFiles.Where(e => e.GalleryId == gallery.Id).OrderByDescending(e => e.DateUploaded);
            gallery.GalleryFiles = files.ToList();
        }

        return View(gallery);
    }
    
    public async Task<IActionResult> Logout()
    {
        await _signInManager.SignOutAsync();
        return RedirectToAction("Index", "Account");
    }

    public async Task<ActionResult> SoloIndex()
    {
        var gallery = await _context.Gallery.FirstOrDefaultAsync();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }

        if (gallery == null)
        {
            gallery = new Models.Gallery.Gallery();
            gallery.Id = Guid.NewGuid().ToString();
            gallery.GalleryFiles = new();
            _context.Gallery.Add(gallery);
            await _context.SaveChangesAsync();
            gallery = await _context.Gallery.FirstOrDefaultAsync();
        }
        else
        {
            var files = _context.GalleryFiles.Where(e => e.GalleryId == gallery.Id).OrderByDescending(x => x.DateUploaded).Where(e => e.category == "Solo");
            gallery.GalleryFiles = files.ToList();
        }

        return View(gallery);
    }
    
    public async Task<ActionResult> FurIndex()
    {
        var gallery = await _context.Gallery.FirstOrDefaultAsync();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }

        if (gallery == null)
        {
            gallery = new Models.Gallery.Gallery();
            gallery.Id = Guid.NewGuid().ToString();
            gallery.GalleryFiles = new();
            _context.Gallery.Add(gallery);
            await _context.SaveChangesAsync();
            gallery = await _context.Gallery.FirstOrDefaultAsync();
        }
        else
        {
            var files = _context.GalleryFiles.Where(e => e.category == "Fur Families").OrderByDescending(x => x.DateUploaded).Where(e => e.GalleryId == gallery.Id);
            gallery.GalleryFiles = files.ToList();
        }

        return View(gallery);
    }
    
    public async Task<ActionResult> FamilyIndex()
    {
        var gallery = await _context.Gallery.FirstOrDefaultAsync();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }

        if (gallery == null)
        {
            gallery = new Models.Gallery.Gallery();
            gallery.Id = Guid.NewGuid().ToString();
            gallery.GalleryFiles = new();
            _context.Gallery.Add(gallery);
            await _context.SaveChangesAsync();
            gallery = await _context.Gallery.FirstOrDefaultAsync();
        }
        else
        {
            var files = _context.GalleryFiles.Where(e => e.category == "Family").OrderByDescending(x => x.DateUploaded).Where(e => e.GalleryId == gallery.Id);
            gallery.GalleryFiles = files.ToList();
        }

        return View(gallery);
    }
    
    public async Task<ActionResult> CoupleIndex()
    {
        var gallery = await _context.Gallery.FirstOrDefaultAsync();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }

        if (gallery == null)
        {
            gallery = new Models.Gallery.Gallery();
            gallery.Id = Guid.NewGuid().ToString();
            gallery.GalleryFiles = new();
            _context.Gallery.Add(gallery);
            await _context.SaveChangesAsync();
            gallery = await _context.Gallery.FirstOrDefaultAsync();
        }
        else
        {
            var files = _context.GalleryFiles.Where(e => e.category == "Couples").OrderByDescending(x => x.DateUploaded).Where(e => e.GalleryId == gallery.Id);
            gallery.GalleryFiles = files.ToList();
        }

        return View(gallery);
    }

}

YourStudioFinal/Views/Gallery/Child.cshtml
@page
@model YourStudioFinal.Views.Gallery.Child

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    
</div>
</body>
</html>

YourStudioFinal/Views/Gallery/Couple.cshtml
@page
@model YourStudioFinal.Views.Gallery.Couple

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    
</div>
</body>
</html>

YourStudioFinal/Views/Gallery/CoupleAdminIndex.cshtml
@{

    ViewBag.Title = "Gallery Admin";
    
    if (ViewBag.Error != null)
    {
        <script>
            alert("@ViewBag.Error");
        </script>
    }

}


<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" href="~/css/homegallery/galleryadmin.css" asp-append-version="true" />




    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>



    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

</head>


<body>
    <header>
    </header>

    <main>
        <h1 class="text-center">
            <span class="gall">GALLERY</span>

        </h1>
        <br />



        <div class="text-center">
            <div class="nav2list-position">
                <ul class="nav2list">
                    <li class="nav2">

                        @Html.ActionLink("All", "Index", "Gallery", null, new { @class = "black-text" }) &nbsp;         |
                    </li>
                    <li class="nav2">
                        &nbsp; @Html.ActionLink("SoloIto", "SoloAdminIndex", "Gallery", null, new { @class = "black-text" })  &nbsp;    |
                    </li>
                    <li class="nav2">
                        &nbsp; @Html.ActionLink("Family", "FamilyAdminIndex", "Gallery", null, new { @class = "black-text" })   &nbsp;     |
                    </li>
                    <li class="nav2">
                        &nbsp; @Html.ActionLink("Duo", "FurAdminIndex", "Gallery", null, new { @class = "black-text" })  &nbsp;       |

                    </li>
                    <li class="nav2">
                        &nbsp;  @Html.ActionLink("Barkada", "CoupleAdminIndex", "Gallery", null, new { @class = "black-text", @style = "color: #d18d06" }) &nbsp;

                    </li>

                </ul>


            </div>
        </div>



        <div class="wrap">
            <div class="btn-size">
                <div class="dropdown">
                    <button class="button" type="button" data-toggle="modal" data-target="#exampleModalCenter">
                        Add
                    </button>
                    <button class="button1" type="button" onclick="setDelete()">
                        Delete
                    </button>
                </div>
            </div>
        </div>


        <!-- Modal -->
        <div class="modal fade" id="exampleModalCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
            <div class="modal-dialog modal-dialog-centered" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <h5 class="modal-title uploadheader" id="exampleModalLongTitle">Upload Images</h5>
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                    <div class="modal-body">
                        <form id="imageUpload" enctype="multipart/form-data" asp-action="Upload">
                            <label for="category" class="categoryheader">Category:</label>
                            <select name="category" id="category" value="None" class="categoryselect" form="imageUpload">
                                <option value="None"> - Choose - </option>
                                <option value="Solo">SoloIto</option>
                                <option value="Family">Family</option>
                                <option value="Fur Families">Duo</option>
                                <option value="Couples">Barkada</option>

                            </select>
                            <p style="text-align:center; font-size:17px; color:grey">Maximum size limit is 1 Gigabyte..</p>
                            <div class="inlinedisplay">
                                <label for="image" class="imageuploadheader">Choose Files:</label>

                                <input type="file" name="image" id="image" class="form-control-file" accept="image/*" multiple required />
                            </div>
                            <div class="modal-footer">
                                <button type="submit" class="buttonupload">Upload</button>
                            </div>
                        </form>

                    </div>

                </div>
            </div>
        </div>


        <!-- JavaScript Section -->
        <script>


            // JavaScript to handle the upload button click
            $('#uploadBtn').click(function () {
                // Get the file input element
                const fileInput = document.getElementById('imageUpload');

                // Check if a file is selected
                if (fileInput.files.length > 0) {
                    const file = fileInput.files[0];
                    console.log('Uploading file:', file.name);

                    // Here you can perform your file upload logic
                    // For demonstration, we'll just alert a message
                    alert('File uploaded: ' + file.name);

                    // You can also close the modal after upload
                    $('#addModal').modal('hide');
                } else {
                    // No file selected, you can handle this case as needed
                    alert('Please select a file.');
                }
                $(this).prop('disabled', true);
            });
        </script>

        <script>
            document.getElementById('imageUpload').addEventListener('submit', function (event) {
                var category = document.getElementById('category').value;
                if (category === "None") {
                    event.preventDefault();
                    alert('Please select a category.');
                }
            });

            document.getElementById('imageUpload').addEventListener('submit', function (event) {
                var files = document.getElementById('image').files;
                var maxFileSize = 1024 * 1024 * 1024; // 1 GB in bytes
                var totalSize = 0;

                for (var i = 0; i < files.length; i++) {
                    totalSize += files[i].size;
                }

                if (totalSize > maxFileSize) {
                    event.preventDefault();
                    alert('The total size of the files exceeds the limit of 1 GB.');
                }
            });
        </script>

        <div>
            <div class="container">
                @{
                    if (Model.GalleryFiles.Count == 0)
                    {
                        <text>
                            <p class="noitems"> No items found </p>
                        </text>
                    }
                    else
                    {
                        <form id="deleteContent" method="post">
                            @for (int i = 0; i < Model.GalleryFiles.Count; i++)
                            {
                                <div class="responsive">
                                    <input type="checkbox" data-id=@Model.GalleryFiles[i].Id onclick="setDelete" />
                                    <div class="gallery">
                                        <a target="_blank">
                                            <img src="@System.IO.Path.Combine("../uploads", Model.GalleryFiles[i].fileName)" alt="Gallery Image">
                                            @* <img src="@(System.IO.Path.Combine("uploads", Model.GalleryFiles[i].fileName).TrimEnd() + ".ashx?w=600&h=400")" alt="Forest" width="600" height="400"> *@
                                        </a>
                                    </div>
                                </div>
                            }
                        </form>
                    }
                }
            </div>
        </div>

    </main>



    <footer>
        <div class="footer-container">
            <hr />
            <div class="social-icons">
                <a href="https://www.waze.com/live-map/directions?to=ll.14.451163%2C120.951211" target="_blank"><i class="fab fa-waze fa-2x"></i></a>
                <a href="https://www.facebook.com/YourStudio.bacoor" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a>
                <a href="https://www.instagram.com/yourstudio.bacoor/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
            </div>
        </div>
        <p class="copyright">&copy; 2023 Your Studio</p>
    </footer>






    <script src="https://cdjns.cloudflare.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>

    <!-- Compiled and minified JavaScript -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>


    <script>
        setDelete = function () {
            var checked = document.querySelectorAll('input[type="checkbox"]:checked');
            var deleteContent = document.getElementById('deleteContent');
        
            if (checked.length === 0) {
                alert('Please select at least one item to delete.');
            }
            else {
                var confirmation = confirm("Are you sure you want to delete this image?");
                if (confirmation) {
                    deleteContent.action = '/Gallery/Delete?ids=' + Array.from(checked).map(x => x.getAttribute('data-id')).join(',');
                    deleteContent.submit();
                }
            }
        }
    </script>



</body>



</html>

YourStudioFinal/Views/Gallery/Family.cshtml
@page
@model YourStudioFinal.Views.Gallery.Family

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    
</div>
</body>
</html>

YourStudioFinal/Views/Gallery/Fur Families.cshtml
@page
@model YourStudioFinal.Views.Gallery.Fur_Families

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    
</div>
</body>
</html>

YourStudioFinal/Views/Gallery/Solo.cshtml
@page
@model YourStudioFinal.Views.Gallery.Solo

@{
    Layout = null;
}

<!DOCTYPE html>

<html>
<head>
    <title></title>
</head>
<body>
<div>
    
</div>
</body>
</html>