YourStudioFinal/Controllers/Booking/BookingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SendGrid;
using SendGrid.Helpers.Mail;
using YourStudioFinal.data;
using YourStudioFinal.Models;
using YourStudioFinal.Models.Booking;

namespace YourStudioFinal.Controllers.Booking;

public class BookingController : Controller
{
    private readonly UserManager<User> _userManager;
    private readonly SignInManager<User> _signInManager;
    private readonly ApplicationDbContext _context;
    public BookingController(UserManager<User> userManager, SignInManager<User> signInManager, ApplicationDbContext context)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _context = context;
    }

    public async Task<IActionResult> Payment()
    {
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
            TempData["Error"] = "You need to login to access this page";
            return RedirectToAction("Index", "Account");
        }
        return View(_context.Booking.Where(x => x.accountUser.Id == UserDetails.Id).Where(x => x.status == "Accepted").Include(x => x.accountUser).Include(x => x.payment).ToList());
    }

	// GET
	public async Task<ActionResult> Index()
	{
		var UserDetails = await _userManager.GetUserAsync(User);
		if (UserDetails != null)
		{
			ViewBag.User = UserDetails;
			ViewBag.isLogged = true;
		}
		else
		{
			ViewBag.isLogged = false;
			TempData["Error"] = "You need to login to access this page";
			return RedirectToAction("Index", "Account");
		}

		ViewBag.Bookings = _context.Booking
	   .Where(x => x.accountUser.Id == UserDetails.Id)
	   .ToList();

		ViewBag.AllAccountBookings = _context.Booking
		   .Include(x => x.accountUser)
		   .ToList();


		return View();
	}

	// public async Task<ActionResult> Index(string package)
	// {
	//     var UserDetails = await _userManager.GetUserAsync(User);
	//     if (UserDetails != null)
	//     {
	//         ViewBag.User = UserDetails;
	//         ViewBag.isLogged = true;
	//     }
	//     else
	//     {
	//         ViewBag.isLogged = false;
	//         TempData["Error"] = "You need to login to access this page";
	//         return RedirectToAction("Index", "Account");
	//     }
	//     ViewBag.selectedPackage = package;
	//     return View();
	// }

	[Authorize(Roles = "User, Admin")]
    [HttpPost]
    public async Task<IActionResult> AddBooking(BookingModel bookingModel, [FromForm(Name = "image")]IFormFile image)
    {
        bookingModel.dateCreated = DateTime.Now;
        bookingModel.status = "Pending";
        bookingModel.accountUser = _userManager.GetUserAsync(HttpContext.User).Result;
        // new PaymentModel();
        // var Payment = new PaymentModel();
        // if (image != null)
        // {
        //     var fileName = Path.GetFileName(image.FileName);
        //     var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", fileName);
        //     using (var fileStream = new FileStream(filePath, FileMode.Create))
        //     {
        //         await image.CopyToAsync(fileStream);
        //     }
        //     Payment.fileName = fileName;
        //     Payment.Booking = bookingModel;
        //     bookingModel.payment = Payment;
        //     bookingModel.paymentID = Payment.Id;
        //     _context.Add(Payment);
        // }
        _context.Add(bookingModel);
        _context.SaveChanges();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        
        //customer side email
        var apiKey = "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";
        var client = new SendGridClient(apiKey);
        var from_email = new EmailAddress("yourstudio.bacoor@gmail.com", "YourStudio");
        var subject = "Booking Confirmation";
        var userEmail = UserDetails.Email;
        var to_email = new EmailAddress(userEmail);
        var bookingID = bookingModel.Id;
        var htmlContent2 = "<div style=background-image:url(https://i.imgur.com/ak8FrvS.png);padding:20px;text-align:center;list-style-type:none><img src=https://i.imgur.com/Grjb8On.png style=height:30%><h1 style=color:#343a40>New Booking has been made!</h1><h4>We hope this message find you well.</h4><br><h4>We wish to inform you that your recent booking with us is currently pending confirmation. Please be assured that our team is diligently working to finalize your booking.</h4><br><h4>We kindly ask for your patience during the process. Rest assured, we will notify you promptly once your booking is confirmed.</h4><br><h1>Booking Details:</h1><h3>Booking ID: " + bookingID + "</h3><h3>Customer Email: " + userEmail + "</h3><h3>Booking Date: " + bookingModel.date + "</h3><h3>Booking Time: " + bookingModel.time + "</h3><h3>Booking Package: " + bookingModel.packages + "</h3><h3>Booking Add-ons: " + bookingModel.addOns + "</h3><h3>Best Regards!</h3><h3>Your Studio</h3></div>";
        // var totalPrice = bookingModel.totalPrice;
        var plainTextContent = "Booking Success! please wait if your booking was accepted through the same email!" 
                               + Environment.NewLine 
                               + Environment.NewLine
                               + "Your Booking ID is: " + bookingID
                               + Environment.NewLine 
                               + "You can serve it as a receipt if anything goes wrong." 
                               + Environment.NewLine 
                               + Environment.NewLine 
                               + "Please wait for the confirmation email."
                               + Environment.NewLine
                               + Environment.NewLine
                               + "Thank you for choosing YourStudio!"; ;
        // var msg = MailHelper.CreateSingleEmail(from_email, to_email, subject, "", htmlContent2);
        // var response = await client.SendEmailAsync(msg).ConfigureAwait(false);
        
        // admin side email
         var apiKeyAdmin = "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";
         var clientAdmin = new SendGridClient(apiKeyAdmin);
         var from_emailAdmin = new EmailAddress("yourstudio.bacoor@gmail.com", "YourStudioSystem");
         var to_emailAdmin = new EmailAddress("yourstudio.bacoor@gmail.com");
         var subjectAdmin = "Booking Notification";
         var htmlContent = "<div style='background-image:url(https://i.imgur.com/ak8FrvS.png);padding:20px;text-align:center;list-style-type:none;font-family:\"Libre Franklin\"'><img src=https://i.imgur.com/Grjb8On.png style=height:30%><h1 style=color:#343a40>New Booking has been made!</h1><h1>Booking Details:</h1><h3>Booking ID: " + bookingID + "</h3><h3>Customer Email: " + userEmail + "</h3><h3>Booking Date: " + bookingModel.date + "</h3><h3>Booking Time: " + bookingModel.time + "</h3><h3>Booking Package: " + bookingModel.packages + "</h3><h3>Booking Add-ons: " + bookingModel.addOns + "</h3></div>";
         var plainTextContentAdmin = "New Booking has been made! Please check the admin panel for more details."
                                     + Environment.NewLine
                                     + "Booking Details: "
                                     + Environment.NewLine
                                     + "Booking ID: " + bookingID
                                     + Environment.NewLine
                                     + "Customer Email: " + userEmail
                                     + Environment.NewLine
                                     + "Booking Date: " + bookingModel.date
                                     + Environment.NewLine
                                     + "Booking Time: " + bookingModel.time
                                     + Environment.NewLine
                                     + "Booking Package: " + bookingModel.packages
                                     + Environment.NewLine
                                     + "Booking Add-ons: " + bookingModel.addOns;
                                     var msgAdmin = MailHelper.CreateSingleEmail(from_emailAdmin, to_emailAdmin, subject, "", htmlContent);
         var responseAdmin = await clientAdmin.SendEmailAsync(msgAdmin).ConfigureAwait(false);
        return RedirectToAction("Index");
    }
    
    //Delete Booking Function
    public async Task<IActionResult> DeleteBooking(string Id)
    {
        var bookingmodel = _context.Booking.FirstOrDefault(x => x.Id == Id);
        if (bookingmodel != null)
        {
            _context.Remove(bookingmodel);
            _context.SaveChanges();
        }

        return RedirectToAction("BList");
    }

    public async Task<IActionResult> submitPayment([FromForm(Name = "image")] IFormFile image, string Id)
    {
        var booking = _context.Booking.FirstOrDefault(x => x.Id == Id);
        if (booking != null)
        {
            var UserDetails = await _userManager.GetUserAsync(User);
            var fileName = Path.GetFileName(image.FileName);
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", fileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                await image.CopyToAsync(fileStream);
            }
            var payment = new PaymentModel();
            payment.fileName = fileName;
            payment.Booking = booking;
            booking.payment = payment;
            booking.paymentID = payment.Id;
            booking.status = "RTP";
            _context.Add(payment);
            _context.Update(booking);
            _context.SaveChanges();
            

YourStudioFinal/Controllers/Inquiry/InquiryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YourStudioFinal.data;
using YourStudioFinal.Models;

namespace YourStudioFinal.Controllers;

// [Authorize]
public class InquiryController : Controller
{
    private readonly ILogger<InquiryController> _logger;

    private readonly ApplicationDbContext _context;

    private readonly UserManager<User> _userManager;

    public InquiryController(ILogger<InquiryController> logger, ApplicationDbContext context, UserManager<User> userManager)
    {
        _userManager = userManager;
        _context = context;
        _logger = logger;
    }
    public async Task<ActionResult> clientInquiry()
    {
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }
        return View();
    }

    [HttpPost]
    public ActionResult Submit(Inquiry inquiry)
    {
        inquiry.accountUser = _userManager.GetUserAsync(HttpContext.User).Result;
        _context.Add(inquiry);
        _context.SaveChanges();
        return RedirectToAction("clientInquiry");
    }

    public ActionResult Inquirylist()
    {
        ViewBag.isLogged = false;
        return View();
    }
    [Authorize(Roles = "Admin")]
    public async Task<ActionResult> iListAdmin()
    {
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails == null)
        {
            TempData["Error"] = "You need to login to access this page";
            return RedirectToAction("Index", "Account");
        }

        ViewBag.User = UserDetails;
        ViewBag.isLogged = true;

        var inquiries = _context.Inquiries.Include(e => e.accountUser).ToList();
        return View(inquiries);
    }

    public async Task<ActionResult> Delete(string id)
    {
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails == null)
        {
            TempData["Error"] = "You need to login to access this page";
            return RedirectToAction("Index", "Account");
        }

        ViewBag.User = UserDetails;
        ViewBag.isLogged = true;

        var inquiry = _context.Inquiries.Find(id);
        _context.Inquiries.Remove(inquiry);
        _context.SaveChanges();
        return RedirectToAction("iListAdmin");
    }

}

YourStudioFinal/Controllers/Packages/PackagesController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using YourStudioFinal.data;
using YourStudioFinal.Models;

namespace YourStudioFinal.Controllers.Packages;

public class PackagesController : Controller
{
    private readonly UserManager<User> _userManager;
    private readonly SignInManager<User> _signInManager;
    private readonly ApplicationDbContext _context;
    public PackagesController(UserManager<User> userManager, SignInManager<User> signInManager, ApplicationDbContext context)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _context = context;
    }
    public async Task<IActionResult> Index()
    {
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }
        return View();
    }
    
    public async Task<IActionResult> goToBooking()
    {
        return RedirectToAction("Index", "Booking");
    }
}

YourStudioFinal/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>YourStudio - @ViewData["Title"]</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />

    <link rel="stylesheet" href="~/css/homegallery/nav.css" asp-append-version="true" />

    <link rel="icon" href="~/logo.ico" type="image/x-icon" />
    
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css" integrity="sha512-DTOQO9RWCH3ppGqcWaEA1BIZOC6xxalwEsw9c2QQeAIftl+Vegovlnee1c9QX4TctnWMn13TZye+giMm8e2LwA==" crossorigin="anonymous" referrerpolicy="no-referrer" />

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.14.7/dist/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.3.1/dist/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
</head>
<body>
    <header>
        <div class="wrapper-nav">

            <nav class="navbar navbar-expand-lg navbar-light">

                <div class="container-fluid">
                    <a class="navbar-brand" asp-action="Index" asp-controller="Home">
                        <img src="~/nobg.png" alt="Logo" width="150" style="margin-left:70px">
                    </a>
                    <div class="navbar-header">
                        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                            <i class="fas fa-bars"></i>
                        </button>

                    </div>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">

                        <ul class="navbar-nav ml-auto navbar-right">


                            <li class="nav-item active">
                                <a class="nav-link" asp-controller="Home" asp-action="Index">Home</a>
                            </li>

                            @if (User.IsInRole("User") || ViewBag.isLogged == false)
                            {

                                <li class="nav-item active">
                                    <a class="nav-link" asp-controller="GalleryCustomer" asp-action="Index">Gallery</a>
                                </li>

                            }

                            @if (User.IsInRole("Admin"))
                            {
                                <li class="nav-item dropdown active navactive">
                                    <a class="nav-link dropdown-toggle navactive" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Gallery
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="GalleryCustomer" asp-action="Index">User Gallery UI</a>
                                        <a class="dropdown-item" asp-controller="Gallery" asp-action="Index">Admin Gallery</a>
                                    </div>
                                </li>
                            }

                            <li class="nav-item active ">
                                <a class="nav-link" asp-controller="Packages" asp-action="Index">Packages</a>
                            </li>

                            @if (User.IsInRole("User") || ViewBag.isLogged == false)
                            {
                                <li class="nav-item dropdown active">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Booking
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="Booking" asp-action="Index">Create Booking</a>
                                        <a class="dropdown-item" asp-controller="Booking" asp-action="BookingAll">Booking List</a>
                                        <a class="dropdown-item" asp-controller="Booking" asp-action="Payment">Pay your Booking</a>
                                    </div>
                                </li>
                            }

                            @if (User.IsInRole("Admin"))
                            {

                                <li class="nav-item dropdown active">
                                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        Booking
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                        <a class="dropdown-item" asp-controller="Booking" asp-action="Index">Create Booking</a>
                                        <a class="dropdown-item" asp-controller="Booking" asp-action="BList">Review Customer Booking</a>
                                        <a class="dropdown-item" asp-controller="Booking" asp-action="BookingListAdminAccepted">Admin Booking List</a>
                                    </div>
                                </li>
                            }

                            <li class="nav-item active ">
                                <a class="nav-link" asp-controller="Inquiry" asp-action="clientInquiry">FAQ</a>
                            </li>

                            @if (ViewBag.isLogged == false)
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Account" asp-action="Index"><i class="fa-solid fa-door-closed"></i></a>
                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a class="nav-link" asp-controller="Home" asp-action="Logout"><i class="fa-solid fa-door-open"></i></a>
                                </li>
                            }
                        </ul>
                        <script>
                            $(document).ready(function () {
                                $('.nav-link.dropdown-toggle').on('click', function (e) {
                                    e.preventDefault();
                                    $(this).next('.dropdown-menu').slideToggle();
                                });
                            });
                        </script>
                    </div>
                </div>

            </nav>

        </div>
    </header>
    <div class="">
        <main role="main" class="">
            @RenderBody()
        </main>
        <!-- Messenger Chat Plugin Code -->
        <div id="fb-root"></div>

        <div id="fb-customer-chat" class="fb-customerchat"></div>

        <script>
            var chatbox = document.getElementById('fb-customer-chat');
            chatbox.setAttribute("page_id", "122107625090002233");
            chatbox.setAttribute("attribution", "biz_inbox");
        </script>


        <script>
            window.fbAsyncInit = function () {
                FB.init({
                    xfbml: true,
                    version: 'v19.0'
                });
            };

            (function (d, s, id) {
                var js, fjs = d.getElementsByTagName(s)[0];
                if (d.getElementById(id)) return;
                js = d.createElement(s); js.id = id;
                js.src = 'https://connect.facebook.net/en_US/sdk/xfbml.customerchat.js';
                fjs.parentNode.insertBefore(js, fjs);
            }(document, 'script', 'facebook-jssdk'));
        </script>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script async defer crossOrigin="anonymous" src="https://connect.facebook.net/en_US/sdk.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>