YourStudioFinal/Models/Inquiry/Inquiry.cs
using System.ComponentModel.DataAnnotations;

namespace YourStudioFinal.Models;

public class Inquiry
{
    [Key] //primary key
    public string Id { get; set; } = Guid.NewGuid().ToString();
    
    public DateTime Date { get; set; } = DateTime.Now;
    public string userID { get; set; } //userID from user table
    public User accountUser{ get; set; }
    public string Name { get; set; }
    public string Message { get; set; }
}

YourStudioFinal/Controllers/Booking/BookingController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using SendGrid;
using SendGrid.Helpers.Mail;
using YourStudioFinal.data;
using YourStudioFinal.Models;
using YourStudioFinal.Models.Booking;

namespace YourStudioFinal.Controllers.Booking;

public class BookingController : Controller
{
    private readonly UserManager<User> _userManager;
    private readonly SignInManager<User> _signInManager;
    private readonly ApplicationDbContext _context;
    public BookingController(UserManager<User> userManager, SignInManager<User> signInManager, ApplicationDbContext context)
    {
        _userManager = userManager;
        _signInManager = signInManager;
        _context = context;
    }

    public async Task<IActionResult> Payment()
    {
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
            TempData["Error"] = "You need to login to access this page";
            return RedirectToAction("Index", "Account");
        }
        return View(_context.Booking.Where(x => x.accountUser.Id == UserDetails.Id).Where(x => x.status == "Accepted").Include(x => x.accountUser).Include(x => x.payment).ToList());
    }

	// GET
	public async Task<ActionResult> Index()
	{
		var UserDetails = await _userManager.GetUserAsync(User);
		if (UserDetails != null)
		{
			ViewBag.User = UserDetails;
			ViewBag.isLogged = true;
		}
		else
		{
			ViewBag.isLogged = false;
			TempData["Error"] = "You need to login to access this page";
			return RedirectToAction("Index", "Account");
		}

		ViewBag.Bookings = _context.Booking
	   .Where(x => x.accountUser.Id == UserDetails.Id)
	   .ToList();

		ViewBag.AllAccountBookings = _context.Booking
		   .Include(x => x.accountUser)
		   .ToList();


		return View();
	}

	// public async Task<ActionResult> Index(string package)
	// {
	//     var UserDetails = await _userManager.GetUserAsync(User);
	//     if (UserDetails != null)
	//     {
	//         ViewBag.User = UserDetails;
	//         ViewBag.isLogged = true;
	//     }
	//     else
	//     {
	//         ViewBag.isLogged = false;
	//         TempData["Error"] = "You need to login to access this page";
	//         return RedirectToAction("Index", "Account");
	//     }
	//     ViewBag.selectedPackage = package;
	//     return View();
	// }

	[Authorize(Roles = "User, Admin")]
    [HttpPost]
    public async Task<IActionResult> AddBooking(BookingModel bookingModel, [FromForm(Name = "image")]IFormFile image)
    {
        bookingModel.dateCreated = DateTime.Now;
        bookingModel.status = "Pending";
        bookingModel.accountUser = _userManager.GetUserAsync(HttpContext.User).Result;
        // new PaymentModel();
        // var Payment = new PaymentModel();
        // if (image != null)
        // {
        //     var fileName = Path.GetFileName(image.FileName);
        //     var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", fileName);
        //     using (var fileStream = new FileStream(filePath, FileMode.Create))
        //     {
        //         await image.CopyToAsync(fileStream);
        //     }
        //     Payment.fileName = fileName;
        //     Payment.Booking = bookingModel;
        //     bookingModel.payment = Payment;
        //     bookingModel.paymentID = Payment.Id;
        //     _context.Add(Payment);
        // }
        _context.Add(bookingModel);
        _context.SaveChanges();
        
        var UserDetails = await _userManager.GetUserAsync(User);
        
        //customer side email
        var apiKey = "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";
        var client = new SendGridClient(apiKey);
        var from_email = new EmailAddress("yourstudio.bacoor@gmail.com", "YourStudio");
        var subject = "Booking Confirmation";
        var userEmail = UserDetails.Email;
        var to_email = new EmailAddress(userEmail);
        var bookingID = bookingModel.Id;
        var htmlContent2 = "<div style=background-image:url(https://i.imgur.com/ak8FrvS.png);padding:20px;text-align:center;list-style-type:none><img src=https://i.imgur.com/Grjb8On.png style=height:30%><h1 style=color:#343a40>New Booking has been made!</h1><h4>We hope this message find you well.</h4><br><h4>We wish to inform you that your recent booking with us is currently pending confirmation. Please be assured that our team is diligently working to finalize your booking.</h4><br><h4>We kindly ask for your patience during the process. Rest assured, we will notify you promptly once your booking is confirmed.</h4><br><h1>Booking Details:</h1><h3>Booking ID: " + bookingID + "</h3><h3>Customer Email: " + userEmail + "</h3><h3>Booking Date: " + bookingModel.date + "</h3><h3>Booking Time: " + bookingModel.time + "</h3><h3>Booking Package: " + bookingModel.packages + "</h3><h3>Booking Add-ons: " + bookingModel.addOns + "</h3><h3>Best Regards!</h3><h3>Your Studio</h3></div>";
        // var totalPrice = bookingModel.totalPrice;
        var plainTextContent = "Booking Success! please wait if your booking was accepted through the same email!" 
                               + Environment.NewLine 
                               + Environment.NewLine
                               + "Your Booking ID is: " + bookingID
                               + Environment.NewLine 
                               + "You can serve it as a receipt if anything goes wrong." 
                               + Environment.NewLine 
                               + Environment.NewLine 
                               + "Please wait for the confirmation email."
                               + Environment.NewLine
                               + Environment.NewLine
                               + "Thank you for choosing YourStudio!"; ;
        // var msg = MailHelper.CreateSingleEmail(from_email, to_email, subject, "", htmlContent2);
        // var response = await client.SendEmailAsync(msg).ConfigureAwait(false);
        
        // admin side email
         var apiKeyAdmin = "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";
         var clientAdmin = new SendGridClient(apiKeyAdmin);
         var from_emailAdmin = new EmailAddress("yourstudio.bacoor@gmail.com", "YourStudioSystem");
         var to_emailAdmin = new EmailAddress("yourstudio.bacoor@gmail.com");
         var subjectAdmin = "Booking Notification";
         var htmlContent = "<div style='background-image:url(https://i.imgur.com/ak8FrvS.png);padding:20px;text-align:center;list-style-type:none;font-family:\"Libre Franklin\"'><img src=https://i.imgur.com/Grjb8On.png style=height:30%><h1 style=color:#343a40>New Booking has been made!</h1><h1>Booking Details:</h1><h3>Booking ID: " + bookingID + "</h3><h3>Customer Email: " + userEmail + "</h3><h3>Booking Date: " + bookingModel.date + "</h3><h3>Booking Time: " + bookingModel.time + "</h3><h3>Booking Package: " + bookingModel.packages + "</h3><h3>Booking Add-ons: " + bookingModel.addOns + "</h3></div>";
         var plainTextContentAdmin = "New Booking has been made! Please check the admin panel for more details."
                                     + Environment.NewLine
                                     + "Booking Details: "
                                     + Environment.NewLine
                                     + "Booking ID: " + bookingID
                                     + Environment.NewLine
                                     + "Customer Email: " + userEmail
                                     + Environment.NewLine
                                     + "Booking Date: " + bookingModel.date
                                     + Environment.NewLine
                                     + "Booking Time: " + bookingModel.time
                                     + Environment.NewLine
                                     + "Booking Package: " + bookingModel.packages
                                     + Environment.NewLine
                                     + "Booking Add-ons: " + bookingModel.addOns;
                                     var msgAdmin = MailHelper.CreateSingleEmail(from_emailAdmin, to_emailAdmin, subject, "", htmlContent);
         var responseAdmin = await clientAdmin.SendEmailAsync(msgAdmin).ConfigureAwait(false);
        return RedirectToAction("Index");
    }
    
    //Delete Booking Function
    public async Task<IActionResult> DeleteBooking(string Id)
    {
        var bookingmodel = _context.Booking.FirstOrDefault(x => x.Id == Id);
        if (bookingmodel != null)
        {
            _context.Remove(bookingmodel);
            _context.SaveChanges();
        }

        return RedirectToAction("BList");
    }

    public async Task<IActionResult> submitPayment([FromForm(Name = "image")] IFormFile image, string Id)
    {
        var booking = _context.Booking.FirstOrDefault(x => x.Id == Id);
        if (booking != null)
        {
            var UserDetails = await _userManager.GetUserAsync(User);
            var fileName = Path.GetFileName(image.FileName);
            var filePath = Path.Combine(Directory.GetCurrentDirectory(), "wwwroot", "uploads", fileName);
            using (var fileStream = new FileStream(filePath, FileMode.Create))
            {
                await image.CopyToAsync(fileStream);
            }
            var payment = new PaymentModel();
            payment.fileName = fileName;
            payment.Booking = booking;
            booking.payment = payment;
            booking.paymentID = payment.Id;
            booking.status = "RTP";
            _context.Add(payment);
            _context.Update(booking);
            _context.SaveChanges();
            

YourStudioFinal/Controllers/Inquiry/InquiryController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using YourStudioFinal.data;
using YourStudioFinal.Models;

namespace YourStudioFinal.Controllers;

// [Authorize]
public class InquiryController : Controller
{
    private readonly ILogger<InquiryController> _logger;

    private readonly ApplicationDbContext _context;

    private readonly UserManager<User> _userManager;

    public InquiryController(ILogger<InquiryController> logger, ApplicationDbContext context, UserManager<User> userManager)
    {
        _userManager = userManager;
        _context = context;
        _logger = logger;
    }
    public async Task<ActionResult> clientInquiry()
    {
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails != null)
        {
            ViewBag.User = UserDetails;
            ViewBag.isLogged = true;
        }
        else
        {
            ViewBag.isLogged = false;
        }
        return View();
    }

    [HttpPost]
    public ActionResult Submit(Inquiry inquiry)
    {
        inquiry.accountUser = _userManager.GetUserAsync(HttpContext.User).Result;
        _context.Add(inquiry);
        _context.SaveChanges();
        return RedirectToAction("clientInquiry");
    }

    public ActionResult Inquirylist()
    {
        ViewBag.isLogged = false;
        return View();
    }
    [Authorize(Roles = "Admin")]
    public async Task<ActionResult> iListAdmin()
    {
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails == null)
        {
            TempData["Error"] = "You need to login to access this page";
            return RedirectToAction("Index", "Account");
        }

        ViewBag.User = UserDetails;
        ViewBag.isLogged = true;

        var inquiries = _context.Inquiries.Include(e => e.accountUser).ToList();
        return View(inquiries);
    }

    public async Task<ActionResult> Delete(string id)
    {
        var UserDetails = await _userManager.GetUserAsync(User);
        if (UserDetails == null)
        {
            TempData["Error"] = "You need to login to access this page";
            return RedirectToAction("Index", "Account");
        }

        ViewBag.User = UserDetails;
        ViewBag.isLogged = true;

        var inquiry = _context.Inquiries.Find(id);
        _context.Inquiries.Remove(inquiry);
        _context.SaveChanges();
        return RedirectToAction("iListAdmin");
    }

}

YourStudioFinal/Views/Inquiry/Inquirylist.cshtml
@model List<YourStudioFinal.Models.Inquiry>
@{
	ViewBag.Title = "Inquiryist";
}

<!DOCTYPE html>
<html>
<head>
	<link href="~/css/Inquiry/iList.css" rel="stylesheet" />

</head>
<body>

    <header>
       
    </header>
	<div id="content-container">
		<div class="left-column">
			<div id="YB">INQUIRY LIST</div>

			@{
				foreach (var inquiry in Model.Select((value, i) => (value, i)))
				{
					<div id="@("btn" + inquiry.i)" class="blist" data-original-color="white" onclick="clickHandler(this.id)">
						<div>
							<h2>@inquiry.value.accountUser.UserName</h2>
							<h5>@inquiry.value.Date.ToShortDateString()</h5>
						</div>
						<h6>@(inquiry.value.Message.Length > 50 ? inquiry.value.Message.Substring(0, 50) + "..." : inquiry.value.Message)</h6>
					</div>
				}
			}
		</div>
		<div class="vertical-line"></div>
		<div class="right-column">
			@{
				foreach (var inquiry in Model.Select((value, i) => (value, i)))
				{
					<div id="@("srvc" + inquiry.i)" style="display: none">
						<div class="inquiry-details">
							<div class="user-info">
								<div class="UserTitle">@inquiry.value.accountUser.UserName</div>
								<div>@inquiry.value.accountUser.Email</div>
							</div>
							<div>
								<div class="date">@inquiry.value.Date.ToShortDateString()</div>
								<div class="time">@inquiry.value.Date.ToShortTimeString()</div>
							</div>
						</div>
						<hr />
						<br />
						<div class="inqTitle"> @inquiry.value.Name</div>
						<div class="message">@inquiry.value.Message</div>
					</div>

				}
			}

		</div>
	</div>

	<script>
		function clickHandler(element) {
			// $("#datepicker").datepicker("setDate", new Date(2023, 7, 5));
			// $(".ftco-section").show();
			// $(".time-container").show();
			// console.log("You clicked btn1");
			// $("[id^='btnT_']").css("background-color", "white");
			// $("#btnT_1300").css("background-color", "gray");
			$("[id^=srvc]").hide();
			$("#srvc" + element.substr(3)).show();

		};
	</script>

</body>
</html>
<footer>
	<div class="footer">
		<hr />
		<div class="social-icons">
			<a href="#" target="_blank"><i class="fas fa-envelope fa-2x"></i></a>
			<a href="#" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a>
			<a href="#" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
		</div>
	</div>
	<p class="copyright">&copy; 2023 Your Studio</p>
</footer>

YourStudioFinal/Views/Inquiry/clientInquiry.cshtml
@{
    ViewBag.Title = "Frequently Asked Questions";
}
<html>
<head>
    <link rel="stylesheet" href="~/css/Inquiry/crtINQ.css" />
</head>

<body>

    <section class="container" style="
    margin-top: 35px;
">
        <section class="FAQcont" id="faq9">
            <span class="additional-text2">TERMS AND CONDITIONS</span>
            <span style="margin-top: -37px;" id="toggleText9" class="clickable-text" onclick="toggleMessage('toggleText9', 'hiddenMessage9')">V</span>

            <div id="hiddenMessage9" class="hidden-message">
                <br />
                <h2>1. Reservation and Booking:</h2>
                <ul>
                    <li>All photo sessions are subject to availability.</li>
                    <li>Bookings must be made in advance through Facebook Messenger, Instagram Direct Messaging, or via the website YourStudio.</li>
                </ul>
                <h2>2. Payment:</h2>
                <ul>
                    <li>A 50% down payment is required at the time of booking to secure the reservation.</li>
                    <li>Down payments are non-refundable, but rescheduling is permitted with prior notice.</li>
                </ul>
                <h2>3. Cancellation Policy:</h2>
                <ul>
                    <li>In the event of cancellation, a refund will not be provided.</li>
                    <li>Cancellations made with at least 48 hours' notice are eligible for rescheduling.</li>
                </ul>
                <h2>4. Studio Use:</h2>
                <ul>
                    <li>The home photo studio is to be used solely for photography purposes.</li>
                    <li>Any damage to equipment or property caused by the client will be the client's responsibility.</li>
                </ul>
                <h2>5. Props and Equipment:</h2>
                <ul>
                    <li>Clients are welcome to bring their own props or use those provided by the studio.</li>
                    <li>Studio equipment must be used responsibly, and any damage will incur additional charges.</li>
                </ul>
                <h2>6. Liability:</h2>
                <ul>
                    <li>The home photo studio owner is not responsible for any injuries or accidents that may occur during the photo session.</li>
                    <li>Clients are responsible for the well-being and supervision of their guests, including minors.</li>
                </ul>
                <h2>7. Privacy:</h2>
                <ul>
                    <li>Clients' privacy is respected, and images will not be shared without explicit consent.</li>
                    <li>The photographer may use select images for promotional purposes with client permission.</li>
                </ul>
                <h2>8. Rescheduling:</h2>
                <ul>
                    <li>Clients may request to reschedule a session with at least 48 hours' notice.</li>
                    <li>The studio owner reserves the right to reschedule due to unforeseen circumstances.</li>
                </ul>
                <h2>9. Code of Conduct:</h2>
                <ul>
                    <li>Clients are expected to conduct themselves in a respectful manner.</li>
                    <li>Inappropriate behavior will result in immediate termination of the photo session.</li>
                </ul>
                <h2>10. Agreement Acceptance:</h2>
                <ul>
                    <li>By booking a session, clients agree to abide by these terms and conditions.</li>
                </ul>
            </div>
            <hr />
        </section>
    </section>

    <section class="container">
        <div class="FAQ">
            <div>FREQUENTLY ASKED QUESTIONS</div>
        </div>

        <br />
        <section class="FAQcont" id="faq1">
            <div><strong>General |</strong> Photo Studio Experience</div>

            <br />
            <span class="additional-text">How do I book a session?</span>
            <span id="toggleText1" class="clickable-text" onclick="toggleMessage('toggleText1', 'hiddenMessage1')">V</span>

            <div id="hiddenMessage1" class="hidden-message">
                <br />
                <span>Visit this link to fill out our booking form <a style="color:blue; text-decoration: underline;" asp-controller="Booking" asp-action="Index">HERE!</a></span>
            </div>

            <hr />
        </section>

        <section class="FAQcont" id="faq2">
            <span class="additional-text">Is there a dressing room at the studio for outfit changes?</span>
            <span id="toggleText2" class="clickable-text" onclick="toggleMessage('toggleText2', 'hiddenMessage2')">V</span>

            <div id="hiddenMessage2" class="hidden-message">
                <br />
                <span><strong>YES!</strong> Feel free to change into your photoshoot attire at the studio</span>
            </div>

            <hr />
        </section>

        <section class="FAQcont" id="faq3">
            <span class="additional-text">Is there parking available outside the studio?</span>
            <span id="toggleText3" class="clickable-text" onclick="toggleMessage('toggleText3', 'hiddenMessage3')">V</span>

            <div id="hiddenMessage3" class="hidden-message">
                <br />
                <span>Yes, there are available parking.</span>
            </div>

            <hr />
        </section>

        <section class="FAQcont" id="faq4">
            <span class="additional-text">What are your open hours?</span>
            <span id="toggleText4" class="clickable-text" onclick="toggleMessage('toggleText4', 'hiddenMessage4')">V</span>

            <div id="hiddenMessage4" class="hidden-message">
                <br />
                <span><strong>Your Studio</strong> is open 9am - 6pm daily </span>
            </div>

            <hr />
        </section>

        <section class="FAQcont" id="faq5">
            <span class="additional-text">Do I need to make a downpayment upon booking?</span>
            <span id="toggleText5" class="clickable-text" onclick="toggleMessage('toggleText5', 'hiddenMessage5')">V</span>

            <div id="hiddenMessage5" class="hidden-message">
                <br />
                <span>Yup! We ask for an <strong>initial deposit of ₱500</strong> to secure your booking (THE REMAINING BALANCE CAN BE PAID ON THE DAY OF THE PHOTOSHOOT) </span>
            </div>

            <hr />
        </section>

        <section class="FAQcont" id="faq6">
            <span class="additional-text">Can we bring a cake for a cake smash set-up during the photoshoot?</span>
            <span id="toggleText6" class="clickable-text" onclick="toggleMessage('toggleText6', 'hiddenMessage6')">V</span>

            <div id="hiddenMessage6" class="hidden-message">
                <br />
                <span><strong>Sure!</strong> We're happy to accommodate it with a cleaning fee of <strong>₱300.</strong></span>
            </div>

            <hr />
        </section>

        <section class="FAQcont" id="faq7">
            <span class="additional-text">Can I bring props for the photoshoot?</span>
            <span id="toggleText7" class="clickable-text" onclick="toggleMessage('toggleText7', 'hiddenMessage7')">V</span>

            <div id="hiddenMessage7" class="hidden-message">
                <br />
                <span><strong>Of course!</strong> We love the creativity!</span>
            </div>

            <hr />
        </section>

        <section class="FAQcont" id="faq8">
            <span class="additional-text">Do you have any reccomendations for a hair & makeup artist?</span>
            <span id="toggleText8" class="clickable-text" onclick="toggleMessage('toggleText8', 'hiddenMessage8')">V</span>

            <div id="hiddenMessage8" class="hidden-message">
                <br />
                <span>Right now, we're not in partnership with any HMUA yet, but we'll let you know once we are</span>
            </div>

            <hr />
        </section>
    </section>

    <script>
        function toggleMessage(toggleTextId, hiddenMessageId) {
            var hiddenMessage = document.getElementById(hiddenMessageId);
            var toggleText = document.getElementById(toggleTextId);
            var currentDisplay = hiddenMessage.style.display;

            hiddenMessage.style.display = (currentDisplay === 'none') ? 'block' : 'none';
            toggleText.innerHTML = (currentDisplay === 'none') ? 'Λ' : 'V';
        }
    </script>


</body>
</html>

<footer>
    <div class="footer-container">
        <hr />
        <div class="social-icons">
            <a href="https://www.waze.com/live-map/directions?to=ll.14.451163%2C120.951211" target="_blank"><i class="fab fa-waze fa-2x"></i></a>
            <a href="https://www.facebook.com/YourStudio.bacoor" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a>
            <a href="https://www.instagram.com/yourstudio.bacoor/" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
        </div>
    </div>
    <p class="copyright">&copy; 2023 Your Studio</p>
</footer>

YourStudioFinal/Views/Inquiry/iListAdmin.cshtml
@model List<YourStudioFinal.Models.Inquiry>
@{
	ViewBag.Title = "Inquiryist";
}

<!DOCTYPE html>
<html>
<head>
	<link href="~/css/Inquiry/iList.css" rel="stylesheet" />

</head>
<body>

    <header>
      
    </header>
	<div id="content-container">
		<div class="left-column">
			<div id="YB">INQUIRY LIST</div>
			@{
				foreach (var inquiry in Model.Select((value, i) => (value, i)))
				{
					<div id="@("btn" + inquiry.i)" class="blist" data-original-color="white" onclick="clickHandler(this.id)">
						<div>
							<h2>@inquiry.value.accountUser.UserName</h2>
							<h5>@inquiry.value.Date.ToShortDateString()</h5>
						</div>
						<h6>@(inquiry.value.Message.Length > 50 ? inquiry.value.Message.Substring(0, 50) + "..." : inquiry.value.Message)</h6>
					</div>
				}
			}
		</div>
		<div class="vertical-line"></div>
		<div class="right-column">
			@{
				
				foreach (var inquiry in Model.Select((value, i) => (value, i)))
				
				{
					<div id="@("srvc" + inquiry.i)" style="display: none">
						<div class="inquiry-details">
							<div class="user-info">
								<div class="UserTitle">@inquiry.value.accountUser.UserName</div>
								<div>@inquiry.value.accountUser.Email</div>
							</div>
							<div>
								<div class="date">@inquiry.value.Date.ToShortDateString()</div>
								<div class="time">@inquiry.value.Date.ToShortTimeString()</div>
							</div>
						</div>
						<hr />
						<br />
						<div class="inqTitle"> @inquiry.value.Name</div>
						<div class="message">@inquiry.value.Message</div>

						<div style="position: absolute; bottom: 0; right: 20px;">
							@Html.ActionLink("Delete", "Delete", "Inquiry", new { id = inquiry.value.Id }, new { @class = "bi bi-trash inline", @id = "btnGR", @style = "color: black;background-color: white;border-color: black;" })
						</div>
					</div>
					
				}
				
			}
		</div>
	</div>

	<script>
		function clickHandler(element) {
			// $("#datepicker").datepicker("setDate", new Date(2023, 7, 5));
			// $(".ftco-section").show();
			// $(".time-container").show();
			// console.log("You clicked btn1");
			// $("[id^='btnT_']").css("background-color", "white");
			// $("#btnT_1300").css("background-color", "gray");
			$("[id^=srvc]").hide();
			$("#srvc" + element.substr(3)).show();

		};

		document.querySelectorAll('.deletebtn').forEach(function (button) {
			button.addEventListener('click', function () {
				var inquiryId = this.getAttribute('data-inquiry-id');

				fetch(`/Inquiry/DeleteInquiry?id=${inquiryId}`, {
					method: 'DELETE'
				})
					.then(response => {
						if (response.ok) {
							// Remove the inquiry element from the DOM upon successful deletion
							var inquiryElement = this.closest('.inquiry-details');
							inquiryElement.remove();
						} else {
							console.error('Failed to delete inquiry');
						}
					})
					.catch(error => {
						console.error('Error deleting inquiry:', error);
					});
			});
		});
	</script>

</body>
</html>
<footer>
	<div class="footer">
		<hr />
		<div class="social-icons">
			<a href="#" target="_blank"><i class="fas fa-envelope fa-2x"></i></a>
			<a href="#" target="_blank"><i class="fab fa-facebook-f fa-2x"></i></a>
			<a href="#" target="_blank"><i class="fab fa-instagram fa-2x"></i></a>
		</div>
	</div>
	<p class="copyright">&copy; 2023 Your Studio</p>
</footer>